config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get '/about' => "public/homes#about"

  delete 'cart_items/remove_all' => "public/cart_items#remove_all"

  post 'orders/confirm' => "public/orders#confirm"
  get 'orders/thanks' => "public/orders#thanks"

  get 'customers/confirm' => "public/customers#confirm"
  patch 'customers/withdraw' => "public/customers#widhdraw"

  scope module: :public do
    resources :addresses, except: [:new, :show]
    resources :orders, except: [:destroy, :update, :edit]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions'
  }

  get '/admin' => "admin/homes#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => "public/searchs#index", as: 'search'

  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:show, :destroy, :new]
    resources :customers, except: [:create, :destroy, :new]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def enum_i18n(enum_name)
    return nil if self.send(enum_name).nil?
    I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{self.send(enum_name)}")
    end


    def self.enums_i18n(enum_name)
        self.send(enum_name.to_s.pluralize).map do |key, value|
            [I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{key}"), value]
        end.to_h
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  #after_initialize :set_default_values

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  attribute :is_active, :boolean, default: true

  #private
  #def set_default_values
    #self.is_active ||= true
  #end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items

    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order
  
  validates :name, :introduction, :price, :image, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: {wait: 0, confirmed: 1, making: 2, ready: 3, complete: 4}
  enum payment: {credit: 0, bank: 1}
  belongs_to :customer
  has_many :order_items

  validates :postal_code, :address, :name, :billing_amount, :order_status, :shipping_cost, :payment, :customer_id, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum making_status: {impossible: 0, wait: 1, making: 2, complete: 3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_edit_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_edit_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def index
    @generated_genre = Genre.new
    @genre = Genre.new
  end

  def edit
    @generated_genre = Genre.new
    @genre = Genre.find(params[:id])
  end

  def create
    @generated_genre = Genre.new(genre_params)
    if @generated_genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.new
      render :index
    end
  end

  def update
    @generated_genre = Genre.find(params[:id])
    if @generated_genre.update(genre_params)
      redirect_to admin_genres_path
    else
      @genre = Genre.find(params[:id])
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  #before_action :authenticate_admin!
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def top

    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
      @from_customer_show = true
    else
      @customer = Customer.new
      @orders = Order.page(params[:page]).per(10)
      @from_customer_show = false
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admin_path
    end
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <% if @customer.errors.any? %>
        <%= render partial: 'admin/errors/error', locals: {model: @customer} %>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <%= form_with model: @customer, url: "/admin/customers/#{@customer.id}", local:true, class:"form-horizontal" do |f| %>
        <div class="form-group row">
          <label class="col-lg-3">会員ID</label>
          <label class="col-lg-3"><%= @customer.id %></label>
        </div>
        <div class="form-group row">
          <label class="col-lg-3">氏名</label>
          <%= f.text_field :last_name, class:"form-control col-lg-3 mr-3" %>
          <%= f.text_field :first_name, class:"form-control col-lg-3" %>
        </div>
        <div class="form-group row">
          <label class="col-lg-3">フリガナ</label>
          <%= f.text_field :last_name_kana, class:"form-control col-lg-3 mr-3" %>
          <%= f.text_field :first_name_kana, class:"form-control col-lg-3" %>
        </div>
        <div class="form-group row">
          <label class="col-lg-3">郵便番号</label>
          <%= f.text_field :postal_code, class:"form-control col-lg-3" %>
        </div>
        <div class="form-group row">
          <label class="col-lg-3">住所</label>
          <%= f.text_field :address, class:"form-control col-lg-9" %>
        </div>
        <div class="form-group row">
          <label class="col-lg-3">電話番号</label>
          <%= f.text_field :telephone_number, class:"form-control col-lg-3" %>
        </div>
        <div class="form-group row">
          <label class="col-lg-3">メールアドレス</label>
          <%= f.email_field :email, class:"form-control col-lg-3" %>
        </div>
        <div class="form-group row form-inline">
          <label class="col-lg-3 ac-edit-is-active-label">会員ステータス</label>
          <%= f.radio_button :is_active, true, class:"form-control" %><label class="mx-1">有効</label><%= f.radio_button :is_active, false, class:"form_control" %><label>退会</label>
        </div>
        <div class="form-group row">
          <label class="col-lg-3"></label>
          <%= f.submit '変更を保存', class:"col-lg-3 btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h2>会員一覧</h2>
  </div>
  <div class="row">
    <div class="col-lg-9 mx-auto d-flex justify-content-center">
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to admin_customer_path(customer.id) do %><%= customer.last_name %><%= customer.first_name %><% end %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_active %>
                  <label class="ac-index-is-active-true">有効</label>
                <% else %>
                  <label class="ac-index-is-active-false">退会</label>
                <% end %>
              </td>
            </tr>
          <% end %>
        </thead>
      </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container-fluid ac-show-container">
  <div class="row">
    <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
  </div>
  <div class="row">
    <div class="col-lg-7 ml-5 pl-5">
      <table class="table table-borderless">
        <tr>
          <td class="col-lg-4">会員ID</td>
          <td class="col-lg-8"><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <% if @customer.is_active %>
              <label class="ac-show-is-active-true">有効</label>
            <% else %>
              <label class="ac-show-is-active-false">退会</label>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row ml-5 mb-3 pl-5">
    <div class="col-lg-7 ml-5">
      <div class="row ml-5">
        <%= link_to '編集する', edit_admin_customer_path(customer_id: @customer.id), class:"btn btn-success col-lg-2" %>
        <label class="col-lg-2"></label>
        <%= link_to '注文履歴一覧を見る', admin_path(customer_id: @customer.id), class:"btn btn-info col-lg-3" %>
      </div>
    </div>
  </div>
</div>