config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get '/about' => "public/homes#about"

  delete 'cart_items/remove_all' => "public/cart_items#remove_all"

  post 'orders/confirm' => "public/orders#confirm"
  get 'orders/thanks' => "public/orders#thanks"

  get 'customers/confirm' => "public/customers#confirm"
  patch 'customers/withdraw' => "public/customers#widhdraw"

  scope module: :public do
    resources :addresses, except: [:new, :show]
    resources :orders, except: [:destroy, :update, :edit]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions'
  }

  get '/admin' => "admin/homes#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => "public/searchs#index", as: 'search'

  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:show, :destroy, :new]
    resources :customers, except: [:create, :destroy, :new]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def enum_i18n(enum_name)
    return nil if self.send(enum_name).nil?
    I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{self.send(enum_name)}")
    end


    def self.enums_i18n(enum_name)
        self.send(enum_name.to_s.pluralize).map do |key, value|
            [I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{key}"), value]
        end.to_h
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  #after_initialize :set_default_values

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  attribute :is_active, :boolean, default: true

  #private
  #def set_default_values
    #self.is_active ||= true
  #end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items

    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order
  
  validates :name, :introduction, :price, :image, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: {wait: 0, confirmed: 1, making: 2, ready: 3, complete: 4}
  enum payment: {credit: 0, bank: 1}
  belongs_to :customer
  has_many :order_items

  validates :postal_code, :address, :name, :billing_amount, :order_status, :shipping_cost, :payment, :customer_id, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum making_status: {impossible: 0, wait: 1, making: 2, complete: 3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def index
    @generated_genre = Genre.new
    @genre = Genre.new
  end

  def edit
    @generated_genre = Genre.new
    @genre = Genre.find(params[:id])
  end

  def create
    @generated_genre = Genre.new(genre_params)
    if @generated_genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.new
      render :index
    end
  end

  def update
    @generated_genre = Genre.find(params[:id])
    if @generated_genre.update(genre_params)
      redirect_to admin_genres_path
    else
      @genre = Genre.find(params[:id])
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  #before_action :authenticate_admin!
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def top

    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
      @from_customer_show = true
    else
      @customer = Customer.new
      @orders = Order.page(params[:page]).per(10)
      @from_customer_show = false
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_status: params[:order][:order_status].to_i)

    #入金確認になったら全ての商品を「製作待ち」に変更
    if @order.confirmed?
      @order.order_items.all.each do |order_item|
        Admin::OrderItemsController.update_making_status(order_item, :wait)
      end
    end

    redirect_to admin_order_path(@order.id)
  end

  def self.update_order_status(order)
    complete = true #全ての商品のステータスが「製作完了」かどうか

    order.order_items.all.each do |order_item|
      #1個でも製作中ならorderの「製作ステータス」を「製作中(making)」にする
      if order_item.making?
        order.making!
        order.save
        return  #抜ける
      #1つでも製作完了してなければcomplete=false
      elsif !order_item.complete?
        complete=false
      end
    end

    #製作完了に変更
    if complete
      order.ready!
      order.save
    end
  end

  private

  def order_update_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admin_path
    end
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/_genres_form.html.erb
  <div>
    <%= form_with model: genre, url: url, local: true, class:"form-horizontal" do |f| %>
      <div class="form-group row">
        <label class="col-lg-3">ジャンル名</label>
        <%= f.text_field :name, placeholder: 'ジャンル名', class:'form-control col-lg-4' %>
        <label class="col-lg-1"></label>
        <%= f.submit text, class:"btn btn-success col-lg-3" %>
      </div>
    <% end %>
  </div>

app/views/admin/genres/edit.html.erb
<div class="container-fluid ag-edit-container">
  <div class="row">
    <h2>ジャンル編集</h2>
  </div>
  <div class="row"></div>
    <div class="col-lg-5">

      <% if @generated_genre.errors.any? %>
        <%= render partial: 'admin/errors/error', locals: {model: @generated_genre} %>
      <% end %>

      <%= render partial: 'genres_form', locals:{genre: @genre, url: admin_genre_path(@genre.id), text: '変更を保存'} %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container-fluid ag-index-container">
  <div class="row">
    <h2>ジャンル一覧・追加</h2>
  </div>
  <div class="row">
    <div class="col-lg-10">

      <% if @generated_genre.errors.any? %>
        <%= render 'admin/errors/error', locals: {model: @generated_genre} %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 ag-index-form-col">
      <%= render partial: 'genres_form', locals:{genre: @genre, url: '/admin/genres', text: '新規登録'} %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>ジャンル</th>
            <th></th>
          </tr>
          <% Genre.all.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to '編集する', edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
            </tr>
          <% end %>
        </thead>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/_items_form.html.erb
<div class="mx-auto">
  <%= form_with model: item, url: url, local:true, class:"form-horizontal" do |f| %>
    <div class="form-group row">
      <label class="col-lg-3">商品画像</label>
      <%= f.attachment_field :image %>
    </div>
    <div class="form-group row">
      <label class="col-lg-3">商品名</label>
      <%= f.text_field :name, placeholder: '商品名', class:"form-control col-lg-7" %>
    </div>
    <div class="form-group row">
      <label class="col-lg-3">商品説明</label>
      <%= f.text_area :introduction, placeholder: 'ここに説明文を記述します', class:"form-control col-lg-7" %>
    </div>
    <div class="form-group row">
      <label class="col-lg-3">ジャンル</label>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--", class:"form-control col-lg-7" %>
    </div>
    <div class="form-group row" >
      <label class="col-lg-3">税抜価格</label>
      <%= f.number_field :price, placeholder: '1000', class:"form-control col-lg-7" %><label>円</label>
    </div>
    <div class="form-group row form-inline">
      <label class="col-lg-3 ai-form-is-active-label">販売ステータス</label>
      <%= f.radio_button :is_active, true, checked: true %><label class="mx-1">販売中</label><%= f.radio_button :is_active, false %><label>売切れ</label>
    </div>
    <div class="row">
      <%= f.submit text, class:"mx-auto btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/items/edit.html.erb
<div class="container-fluid ai-edit-container">
  <div class="row">
    <h2>商品編集</h2>
  </div>
  <div class="row">
    <div class="col-lg-8 mx-auto">

      <% if @item.errors.any? %>
        <%= render partial: 'admin/errors/error', locals: {model: @item} %>
      <% end %>

      <%= render partial: 'items_form', locals:{item: @item, url: "/admin/items/#{@item.id}", text: '変更を保存'} %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container-fluid">
  <div class="row ai-index-title-row">
    <h2>商品一覧</h2>
    <%= link_to "+", new_admin_item_path, class:"ml-auto ai-index-add-button" %>
  </div>
  <div class="row">
    <div class="col-lg-10 mx-auto">
      <table class="table mx-auto">
        <thead>
          <tr class="table-secondary">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= "#{item.price.to_s(:delimited)}" %></td>
              <td><%= "#{Genre.find(item.genre_id).name}" %></td>
              <td>
                <% if item.is_active %>
                  <label class="ai-index-is-active-true">販売中</label>
                <% else %>
                  <label class="ai-index-is-active-false">売切れ</label>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container-fluid ai-new-container">
  <div class="row">
    <h2>商品新規登録</h2>
  </div>
  <div class="row">
    <div class="col-lg-8 mx-auto">

      <% if @item.errors.any? %>
        <%= render partial: 'admin/errors/error', locals: {model: @item} %>
      <% end %>

      <%= render partial: 'items_form', locals:{item: @item, url: '/admin/items', text: '新規登録'} %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container-fluid ai-show-container">
  <div class="row">
    <h2>商品詳細</h2>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-3 ai-show-image-col">
      <%= attachment_image_tag @item, :image %>
    </div>
    <div class="col-lg-3">
      <table class="table table-borderless">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= "#{Genre.find(@item.genre_id).name}" %></td>
        </tr>
        <tr>
          <td>税込価格<br>(税抜価格)</td>
          <% tax = ((@item.price)*1.08).floor %>
          <td><%= "#{tax.to_s(:delimited)}(#{(@item.price).to_s(:delimited)})円" %></td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active %>
              <label class="ai-show-is-active-true">販売中</label>
            <% else %>
              <label class="ai-show-is-active-false">売切れ</label>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row my-5">
    <%= link_to '編集する', edit_admin_item_path(params[:id]), class:"btn btn-success mx-auto col-lg-2" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h2>注文履歴詳細</h2>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="form-group row">
        <label class="col-lg-3"><strong>購入者</strong></label>
        <% customer = Customer.find(@order.customer_id) %>
        <%= link_to admin_customer_path(customer.id), class:"col-lg-3" do %><%= customer.last_name %> <%= customer.first_name %><% end %>
      </div>
      <div class="form-group row">
        <label class="col-lg-3"><strong>注文日</strong></label>
        <label class="col-lg-3"><%= l @order.created_at, format: :short %></label>
      </div>
      <div class="form-group row">
        <label class="col-lg-3"><strong>配送先</strong></label>
        <label class="col-lg-3">
          <%= @order.address %><br>
          <%= @order.name %>
        </label>
      </div>
      <div class="form-group row">
        <label class="col-lg-3"><strong>支払い方法</strong></label>
        <% payment = nil %>
        <% if @order.credit? %>
          <% payment='クレジットカード' %>
        <% elsif @order.bank? %>
          <% payment='銀行振込' %>
        <% end %>
        <label class="col-lg-3"><%= payment %></label>
      </div>
      <%= form_with model: @order, url: "/admin/orders/#{@order.id}", local:true, class:"form-horizontal" do |f| %>
        <div class="form-group row">
          <label class="col-lg-3"><strong>注文ステータス</strong></label>
          <%= f.select :order_status, Order.enums_i18n(:order_status), {selected: @order.order_status_before_type_cast}, {class:"form-control col-lg-3 mx-3"} %>
          <%= f.submit '更新', class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center align-items-end mt-5">
    <% total = 0 %>
    <div class="col-lg-6">
      <table class="table table-borderless">
        <thead>
          <tr class="table-secondary">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_items.all.each do |order_item| %>
            <tr>
              <td><%= "#{Item.find(order_item.item_id).name}" %></td>
              <td><%= "#{(order_item.order_price*1.08).floor.to_s(:delimited)}"  %></td>
              <td><%= order_item.amount %></td>
              <% total += subtotal = (order_item.order_price * (order_item.amount) * 1.08).floor %>
              <td><%= subtotal %></td>
              <td>
                <%= form_with model: order_item, url: admin_order_item_path(order_item.id), local:true, class:"form-horizontal" do |f| %>
                  <div class="form-group row">
                    <%= f.select :making_status, OrderItem.enums_i18n(:making_status), {selected: order_item.making_status_before_type_cast}, {class:"form-control col-lg-7"} %>
                    <%= f.submit '更新', class:"btn btn-success col-lg-3 ml-4" %>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-4">
      <table class="table table-borderless">
        <tr>
          <td><label>商品合計</label></td>
          <td><label><%= "#{total.to_s(:delimited)}" %>円</label></td>
        </tr>
        <tr>
          <td><label>送料</label></td>
          <td><label><%= "#{(@order.shipping_cost).to_s(:delimited)}" %>円</label></td>
        </tr>
        <tr>
          <td><label><strong>請求金額合計</strong></label></td>
          <td><label><strong><%= "#{(@order.billing_amount).to_s(:delimited)}" %>円</strong></label></td>
        </tr>
      </table>
    </div>
  </div>
</div>