config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get '/about' => "public/homes#about"

  delete 'cart_items/remove_all' => "public/cart_items#remove_all"

  post 'orders/confirm' => "public/orders#confirm"
  get 'orders/thanks' => "public/orders#thanks"

  get 'customers/confirm' => "public/customers#confirm"
  patch 'customers/withdraw' => "public/customers#widhdraw"

  scope module: :public do
    resources :addresses, except: [:new, :show]
    resources :orders, except: [:destroy, :update, :edit]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions'
  }

  get '/admin' => "admin/homes#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => "public/searchs#index", as: 'search'

  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:show, :destroy, :new]
    resources :customers, except: [:create, :destroy, :new]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def enum_i18n(enum_name)
    return nil if self.send(enum_name).nil?
    I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{self.send(enum_name)}")
    end


    def self.enums_i18n(enum_name)
        self.send(enum_name.to_s.pluralize).map do |key, value|
            [I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{key}"), value]
        end.to_h
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  #after_initialize :set_default_values

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  attribute :is_active, :boolean, default: true

  #private
  #def set_default_values
    #self.is_active ||= true
  #end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items

    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order
  
  validates :name, :introduction, :price, :image, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: {wait: 0, confirmed: 1, making: 2, ready: 3, complete: 4}
  enum payment: {credit: 0, bank: 1}
  belongs_to :customer
  has_many :order_items

  validates :postal_code, :address, :name, :billing_amount, :order_status, :shipping_cost, :payment, :customer_id, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum making_status: {impossible: 0, wait: 1, making: 2, complete: 3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def index
    @generated_genre = Genre.new
    @genre = Genre.new
  end

  def edit
    @generated_genre = Genre.new
    @genre = Genre.find(params[:id])
  end

  def create
    @generated_genre = Genre.new(genre_params)
    if @generated_genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.new
      render :index
    end
  end

  def update
    @generated_genre = Genre.find(params[:id])
    if @generated_genre.update(genre_params)
      redirect_to admin_genres_path
    else
      @genre = Genre.find(params[:id])
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  #before_action :authenticate_admin!
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def top

    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
      @from_customer_show = true
    else
      @customer = Customer.new
      @orders = Order.page(params[:page]).per(10)
      @from_customer_show = false
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admin_path
    end
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/_all_orders.html.erb
<div>
  <h2>注文履歴一覧</h2>
  <table class="table">
    <thead>
      <tr class="table-secondary">
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% orders.each do |order| %>
        <tr>
          <% customer = Customer.find(order.customer_id) %>
          <% order_items = order.order_items.all %>
          <% amount = 0 %>
          <% order_items.each do |order_item| %>
            <% amount += order_item.amount %>
          <% end %>
          <td><%= link_to admin_order_path(order.id) do %><%= l order.created_at %><% end %></td>
          <td><%= customer.last_name %><%= customer.first_name %></td>
          <td><%= amount %></td>
          <td><%= order.enum_i18n(:order_status) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/homes/_customer_orders.html.erb
<%#ある会員の購入履歴一覧のため、名前は一度表示するのみに変更しました。 %>

<div>
  <h2><%= customer.last_name %><%= customer.first_name %>さんの注文履歴一覧</h2>
  <table class="table">
    <thead>
      <tr class="table-secondary">
        <th>購入日時</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% orders.each do |order| %>
        <tr>
          <% order_items = order.order_items.all %>
          <% amount = 0 %>
          <% order_items.each do |order_item| %>
            <% amount += order_item.amount %>
          <% end %>
          <td><%= link_to admin_order_path(order.id) do %><%= l order.created_at %><% end %></td>
          <td><%= amount %></td>
          <td><%= order.enum_i18n(:order_status) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/homes/top.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <% if !@from_customer_show %>
        <%= render partial: 'all_orders', locals:{orders: @orders} %>
      <% else %>
        <%= render partial: 'customer_orders', locals:{orders: @orders, customer: @customer} %>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @orders %>
  </div>
</div>