config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get '/about' => "public/homes#about"

  delete 'cart_items/remove_all' => "public/cart_items#remove_all"

  post 'orders/confirm' => "public/orders#confirm"
  get 'orders/thanks' => "public/orders#thanks"

  get 'customers/confirm' => "public/customers#confirm"
  patch 'customers/withdraw' => "public/customers#widhdraw"

  scope module: :public do
    resources :addresses, except: [:new, :show]
    resources :orders, except: [:destroy, :update, :edit]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions'
  }

  get '/admin' => "admin/homes#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/search' => "public/searchs#index", as: 'search'

  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, except: [:show, :destroy, :new]
    resources :customers, except: [:create, :destroy, :new]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def enum_i18n(enum_name)
    return nil if self.send(enum_name).nil?
    I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{self.send(enum_name)}")
    end


    def self.enums_i18n(enum_name)
        self.send(enum_name.to_s.pluralize).map do |key, value|
            [I18n.t!("enums.#{self.model_name.i18n_key}.#{enum_name}.#{key}"), value]
        end.to_h
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  #after_initialize :set_default_values

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  attribute :is_active, :boolean, default: true

  #private
  #def set_default_values
    #self.is_active ||= true
  #end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items

    validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order
  
  validates :name, :introduction, :price, :image, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: {wait: 0, confirmed: 1, making: 2, ready: 3, complete: 4}
  enum payment: {credit: 0, bank: 1}
  belongs_to :customer
  has_many :order_items

  validates :postal_code, :address, :name, :billing_amount, :order_status, :shipping_cost, :payment, :customer_id, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum making_status: {impossible: 0, wait: 1, making: 2, complete: 3}
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  #before_action :authenticate_admin!
  skip_before_action :authenticate_customer!
  before_action :authenticate_admin!

  def top

    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).per(10)
      @from_customer_show = true
    else
      @customer = Customer.new
      @orders = Order.page(params[:page]).per(10)
      @from_customer_show = false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admin_path
    end
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6f32c97baa.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="container-fluid border-bottom">
      <div class="row">
        <div class="col-lg-12">
          <nav class="navbar navbar-expand-lg navbar-light">
            <%= link_to "LOGO", '/', class:"navbar-brand logo" %>
            <% if customer_signed_in? %>
              <label>ようこそ、<%= current_customer.last_name %>さん!</label>
            <% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#button-target" aria-controls="button-target" aria-expanded="false" aria-label="Toggle Navigation" >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="button-target">
              <% if !admin_signed_in? && !customer_signed_in? %>
                <ul class="navbar-nav ml-auto">
                  <li>
                    <div class="ml-auto m-3">
                      <label>検索</label>
                      <div class="d-inline-block">
                        <%= form_tag(search_path, :method => 'get') do %>
                          <%= text_field_tag :key %>
                          <%= submit_tag 'Search', :name => nil %>
                        <% end %>
                      </div>
                    </div>
                  </li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to 'About', '/about' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to '商品一覧', '/items' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to '新規登録', '/customers/sign_up' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to 'ログイン', '/customers/sign_in' %></li>
                </ul>
              <% elsif admin_signed_in? %>
                <ul class="navbar-nav ml-auto admin-nav-ul">
                  <li>
                    <div class="ml-auto m-3">
                      <label>検索</label>
                      <div class="d-inline-block">
                        <%= form_tag(search_path, :method => 'get') do %>
                          <%= text_field_tag :key %>
                          <%= submit_tag 'Search', :name => nil %>
                        <% end %>
                      </div>
                    </div>
                  </li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to '商品一覧', '/admin/items' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to '会員一覧', '/admin/customers' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to '注文履歴一覧', admin_path %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to 'ジャンル一覧', '/admin/genres' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
                </ul>
              <% else %>
                <ul class="navbar-nav ml-auto">
                  <li>
                    <div class="ml-auto m-3">
                      <label>検索</label>
                      <div class="d-inline-block">
                        <%= form_tag(search_path, :method => 'get') do %>
                          <%= text_field_tag :key %>
                          <%= submit_tag 'Search', :name => nil %>
                        <% end %>
                      </div>
                    </div>
                  </li>
                  <li class="nav-item nav-link border p-1 m-3"><div><%= link_to 'マイページ', customers_path %></div></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to '商品一覧', '/items' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to 'カート', '/cart_items' %></li>
                  <li class="nav-item nav-link border p-1 m-3"><%= link_to 'ログアウト', '/customers/sign_out', method: :delete %></li>
                </ul>
              <% end %>
            </div>
          </nav>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer class="footer border-top">
      <div class="container-fluid">
      </div>
    </footer>
  </body>
</html>